Console.WriteLine("Cotización Terreno");
Console.Write("Ingrese el valor en metros de la longitud de su terreno: ");
decimal longitud = decimal.Parse(Console.ReadLine());
Console.Write("Ingrese el valor en metros de la anchura de su terreno: ");
decimal anchura = decimal.Parse(Console.ReadLine());
Console.Write("Ingrese el valor del terreno por metro cuadrado: ");
decimal valormetrocuadrado = decimal.Parse(Console.ReadLine());
decimal area = longitud * anchura;
decimal valorTotal = area * valormetrocuadrado;
Console.WriteLine($"El valor total de su terreno es: {valorTotal}");